### ISSUE TITLE
Task 5: UnpicklingError

### ISSUE THREAD

**Issue by mathophil2718** [DCASE-REPO/dcase2018_baseline#12]
Running the baseline code for Task 5, I ran across this error
> Traceback (most recent call last):
>   File "\~/Documents/dcase_util/dcase2018_baseline/task5/task5.py", line 763, in <module>
>     sys.exit(main(sys.argv))
>   File "\~/Documents/dcase_util/dcase2018_baseline/task5/task5.py", line 716, in main
>     overwrite=overwrite
>   File "\~/Documents/dcase_util/dcase2018_baseline/task5/task5.py", line 237, in do_feature_normalization
>     features = dcase_util.containers.FeatureRepository().load(filename=feature_filename)
>   File "\~/anaconda3/lib/python3.6/site-packages/dcase_util/containers/data.py", line 2149, in load
>     super(DataRepository, self).load(filename=self.filename)
>   File "\~/anaconda3/lib/python3.6/site-packages/dcase_util/containers/containers.py", line 502, in load
>     dict.update(self, Serializer.load_cpickle(filename=self.filename))
> _pickle.UnpicklingError: pickle data was truncated

during the Feature Normalization.

For most of the files, this never occurs. This warning is thrown on the extracted file
`output_task5/features/feature_processing_chain_3b4ae3a13a504b182ef406346a732dc6/DevNode3_ex231_16.wav`

I'm running this on Ubuntu 18.04, using:
- Name : Version : Build
- anaconda-client  :         1.6.14 :                  py36_0  
- anaconda-navigator  :      1.8.7         :           py36_0  
- anaconda-project   :       0.8.2       :     py36h44fb852_0 
- cloudpickle          :     0.5.3       :             py36_0  
- pickleshare        :       0.7.4     :       py36h63277f8_0`

My dcase_util is at the master head, version 0.2.3. The dcase2018_baseline is at commit 82fd1e52e834244e5573b1530d0c620eef478fdd. Using `pip install -r requirements.txt` all package requirements are met in Task 5. The only modification I've made is to the dataset path in the task5.yaml.

**Comment by gertdekkers** [comment]
The features are normally saved in a .cpickle format. The file you're mentioning seems to be a .wav file. I'm not sure why this is the case. Are all other files in that folder also with a .wav extension? How are the dataset/feature paths defined?

**Comment by mathophil2718** [comment]
The dataset path is set to `~/Data/DCASE/dataset_task5/`. All other parameters are kept to default. I looked in the folder, all of the files in `output_task5/features/feature_processing_chain_3b4ae3a13a504b182ef406346a732dc6/` have .cpickle extensions, except for the parameters file. There are two hashes in the parameters file.

> _hash: 3b4ae3a13a504b182ef406346a732dc6
> method: DCASE2018_Task5_baseline
> parameters:
>   _hash: 113564d184f826f45da520b7199f70ad

**Comment by gertdekkers** [comment]
Have you tried removing this .wav file in order to do the feature extraction again?
