### ISSUE TITLE
[Task 5] OSError: sndfile library not found

### ISSUE THREAD

**Issue by eshalev4** [DCASE-REPO/dcase2018_baseline#25]
I have freshly installed ubuntu bash on windows 10. I have installed all the requirements using pip. upon typing `python task5.py` I am getting the following error:

Traceback (most recent call last):
  File "task5.py", line 11, in <module>
    import dcase_util
  File "/home/erezsh/.local/lib/python2.7/site-packages/dcase_util/__init__.py", line 6, in <module>
    from . import containers
  File "/home/erezsh/.local/lib/python2.7/site-packages/dcase_util/containers/__init__.py", line 953, in <module>
    from .audio import *
  File "/home/erezsh/.local/lib/python2.7/site-packages/dcase_util/containers/audio.py", line 8, in <module>
    import soundfile
  File "/home/erezsh/.local/lib/python2.7/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

What am I missing?

**Comment by eshalev4** [comment]
Solved by installing with `sudo apt-get install libsndfile1` maybe it should be added to the requierments of dcase_util?

**Comment by toni-heittola** [comment]
Note about this has been now added to the documentation of the dcase_util > https://dcase-repo.github.io/dcase_util/installation.html
